FROM node:10-slim

LABEL "version"="1.0.0"
LABEL "repository"="http://github.com/actions/npm"
LABEL "homepage"="http://github.com/actions/npm/publish"
LABEL "maintainer"="GitHub Actions <support+actions@github.com>"
LABEL "com.github.actions.name"="GitHub Action for npm-publish"
LABEL "com.github.actions.description"="Exposes the npm-publish command as a GitHub Action."
LABEL "com.github.actions.icon"="package"
LABEL "com.github.actions.color"="d73a49"

ENTRYPOINT ["npm"]
CMD ["publish"]
