on:
  [push, pull_request]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Install
      run: |
        npm install
    - name: Test
      run: |
        npm t
    - name: Lint
      run: |
        npm run lint
    - name: Build
      run: |
        npm run build
