on:
  [push, pull_request]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0

    - name: Install
      run: |
        npm install

    - name: Build
      run: |
        npm run lint
        npm run test
        npm run build

    - name: Release
      if: startsWith( github.ref, 'refs/tags/' )
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ./npmrc
        npm --userconfig ./npmrc publish --access public
