on:
  push:
  pull_request:
    types: [opened, synchronize, closed]
  issues:
    types: [edited]

name: TODO

jobs:
  todo:
    name: TODO
    runs-on: ubuntu-latest
    steps:
    - name: Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: TODO
      uses: swinton/todo@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
